sudo: required
services:
  - docker
before_install:
  # Use encypted auth file 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Download and install GCP SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # updates PATH for the GCP SDK
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl 
  - gcloud components update kubectl
  # Auth to account 
  - gcloud auth activate-service-account --key-file service-account.json
