sudo: required
services:
  - docker
env: 
  global:
    - SHA=$(git rev-parse HEAD)

    # Disable all interactive prompts when running gcloud commands.
    # If input is required, defaults will be used, or an error will be raised.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Use encypted auth file 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # Download and install GCP SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # updates PATH for the GCP SDK
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl 
  - gcloud components update kubectl
  # Auth to account 
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project fib-docker-kubernetes
  - gcloud config set compute/zone europe-west1-b	
  - gcloud container clusters get-credentials fib-docker-kubernetes

  # Use travis env vars on the integrated branch to login, echo the password and pickup via pipe
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Use dev build due to all dependencies available 
  - docker build -t razik/react-test -f ./client/Dockerfile.dev ./client

# Run tests 
script:
  - docker run -e CI=true razik/react-test npm test

deploy: 
  provider: script
  script: bash ./deploy.sh
  # Run deployment script only for master branch 
  on:
    branch: master

